Sprite.c
Sprite* create_sprite(xpm_image_t img, int x, int y, int xspeed_, int yspeed_, enum Direction direction_, enum State state_)
Referenced by create_Duck, createCrosshair.
void destroy_sprite(Sprite *sp)
Referenced by gameDestroy, gameReset, update_Duck.
int draw_sprite(Sprite *sp)
Referenced by draw_ducks, drawCrosshair.
void change_Sprite_Img(Sprite *sprite, xpm_image_t img)
Referenced by change_dir, checkDuckGotShot, update_direction, update_Duck.