database.c
Database* db
Referenced by create_Duck, createCrosshair, createDucksArray, draw_fullScore, drawBackground, drawCrosshair, drawLives, drawMainMenu, drawNumber, drawPausedIndicator, gameDestroy, gameInit, gameReset, getDB, handlePause, loadAllXPMs, proj_main_loop, updateCurrentSelect.
void loadAllXPMs()
References db.
Referenced by proj_main_loop.
Database* getDB()
References db.
Referenced by change_dir, checkDuckGotShot, create_Duck, draw_ducks, drawLives, drawScoreDigits, proj_main_loop, update_direction, update_Duck, update_ducks_dir, update_ducks_status.
void gameInit()
References createCrosshair, createDucksArray, db.
Referenced by proj_main_loop.
void gameReset()
References db, destroy_sprite.
Referenced by proj_main_loop.
void gameDestroy()
References db, destroy_sprite.
Referenced by proj_main_loop.
void createCrosshair()
References create_sprite, db.
Referenced by gameInit.
void createDucksArray()
References db.
Referenced by gameInit.
void create_Duck()
References create_sprite, db, getDB.
Referenced by proj_main_loop.
void drawMainMenu()
References db.
Referenced by proj_main_loop.
void drawBackground(uint32_t h, uint32_t m)
References db.
Referenced by proj_main_loop.
void drawCrosshair()
References db, draw_sprite.
Referenced by proj_main_loop.
void drawPausedIndicator()
References db.
Referenced by proj_main_loop.
void drawScoreDigits()
References drawNumber, getDB.
Referenced by draw_fullScore.
void draw_fullScore()
References db, drawScoreDigits.
Referenced by proj_main_loop.
void draw_fullLives()
References drawLives.
Referenced by proj_main_loop.
void drawLives()
References db, getDB.
Referenced by draw_fullLives.
void drawNumber(int number, uint16_t x_pos, uint16_t y_pos)
References db.
Referenced by drawScoreDigits.
void draw_ducks()
References draw_sprite, getDB.
Referenced by proj_main_loop.
void updateCurrentSelect(uint8_t out_b)
References db.
Referenced by proj_main_loop.
void handlePause(uint8_t out_b)
References db.
Referenced by proj_main_loop.