duck.c
void update_ducks_status()
References getDB, update_Duck.
Referenced by proj_main_loop.
void update_ducks_dir()
References getDB, update_direction.
Referenced by proj_main_loop.
enum Direction generate_random_dir(enum Direction direction)
Referenced by update_direction.
void change_dir(Sprite *sprite, enum Direction direction)
References change_Sprite_Img, getDB.
Referenced by update_direction.
void update_direction(Sprite *sprite)
References change_dir, change_Sprite_Img, generate_random_dir, getDB.
Referenced by update_ducks_dir.
void update_Duck(Sprite *sprite, uint8_t idx)
References change_Sprite_Img, destroy_sprite, getDB.
Referenced by update_ducks_status.